# Dense NET1

## Autoencoder

In [1]:
from keras.preprocessing.image import ImageDataGenerator
from keras.layers import Input, Dense, Flatten, Reshape, Dropout, Conv2D, MaxPooling2D, UpSampling2D
from keras.models import Model, Sequential
from keras.utils import plot_model
from keras.callbacks import EarlyStopping
from keras.optimizers import SGD
import time
import numpy as np
import matplotlib.pyplot as plt
import sys

def tuple_generator(generator):
    for batch in generator:
        yield (batch, batch)

np.random.seed(777)
#if (len(sys.argv)<3):
#    print("Input arguments:")
#    print("1. Train images path")
#    print("2. Test images path")
#    exit()
PreTrainImagesPath="D:/SomeData/Caltech101/TrainImages"
PreTestImagesPath="D:/SomeData/Caltech101/TestImages"
TrainImagesPath="D:/SomeData/Caltech101/TrainImages"
TestImagesPath="D:/SomeData/Caltech101/TestImages"
img_width, img_height = 128, 128
epochs = 35
batch_size_1 = 16
batch_size = 32
batch_size_3 = 64
dropout_rate = 0.3
latent_dim = 101

datagen=ImageDataGenerator(rescale=1./255)
pretrain_generator = datagen.flow_from_directory(
        PreTrainImagesPath,
        target_size=(img_width, img_height),
        batch_size=batch_size,
        class_mode=None)
train_samples = pretrain_generator.n

validation_generator = datagen.flow_from_directory(
        PreTestImagesPath,
        target_size=(img_width, img_height),
        batch_size=batch_size,
        class_mode=None)
nb_validation_samples = validation_generator.n

sgd_4 = SGD(lr=0.1, decay=1e-6, momentum=0.9, nesterov=True)
sgd_5 = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
sgd_6 = SGD(lr=0.001, decay=1e-6, momentum=0.9, nesterov=True)

input_img = Input(shape=(img_width, img_height, 3))
x = Flatten(input_shape=(img_width, img_height, 3))(input_img)
encoded = (Dense(units=300, activation='sigmoid', name='dens_sigmoid_1'))(x)
x = Dense(img_width*img_height*3, activation='sigmoid')(encoded)
decoded = Reshape((img_width, img_height, 3), input_shape=(img_width*img_height*3,))(x)
autoencoder_1 = Model(input_img, decoded)
autoencoder_1.compile(optimizer='adadelta', loss='mse')
#print (autoencoder.summary())
autoencoder_1.fit_generator(
        tuple_generator(pretrain_generator),
        steps_per_epoch=train_samples/batch_size_1,
        epochs=epochs
        )
#autoencoder_1.save('DenseAutoEncoderNET1')
autoencoder_1.save_weights('DenseAutoEncoderNET1_weights_1')

#plot_model(autoencoder, to_file='DenseAutoEncoder.png', show_shapes=True, show_layer_names=False, rankdir='LR')

autoencoder_2 = Model(input_img, decoded)
autoencoder_2.compile(optimizer='adadelta', loss='mse')
autoencoder_2.fit_generator(
        tuple_generator(pretrain_generator),
        steps_per_epoch=train_samples/batch_size,
        epochs=epochs
        )
autoencoder_2.save_weights('DenseAutoEncoderNET1_weights_2')

autoencoder_3 = Model(input_img, decoded)
autoencoder_3.compile(optimizer='adadelta', loss='mse')
autoencoder_3.fit_generator(
        tuple_generator(pretrain_generator),
        steps_per_epoch=train_samples/batch_size_3,
        epochs=epochs
        )
autoencoder_3.save_weights('DenseAutoEncoderNET1_weights_3')

autoencoder_4 = Model(input_img, decoded)
autoencoder_4.compile(optimizer=sgd_4, loss='mse')
autoencoder_4.fit_generator(
        tuple_generator(pretrain_generator),
        steps_per_epoch=train_samples/batch_size,
        epochs=epochs
        )
autoencoder_4.save_weights('DenseAutoEncoderNET1_weights_4')

autoencoder_5 = Model(input_img, decoded)
autoencoder_5.compile(optimizer=sgd_5, loss='mse')
autoencoder_5.fit_generator(
        tuple_generator(pretrain_generator),
        steps_per_epoch=train_samples/batch_size,
        epochs=epochs
        )
autoencoder_5.save_weights('DenseAutoEncoderNET1_weights_5')

autoencoder_6 = Model(input_img, decoded)
autoencoder_6.compile(optimizer=sgd_6, loss='mse')
autoencoder_6.fit_generator(
        tuple_generator(pretrain_generator),
        steps_per_epoch=train_samples/batch_size,
        epochs=epochs
        )
autoencoder_6.save_weights('DenseAutoEncoderNET1_weights_6')


Using TensorFlow backend.


Found 6026 images belonging to 101 classes.
Found 2651 images belonging to 101 classes.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Epoch 1/35
377/376 [==============================] - 119s - loss: 0.1024   
Epoch 2/35
377/376 [==============================] - 14s - loss: 0.1018    
Epoch 3/35
377/376 [==============================] - 14s - loss: 0.1008    
Epoch 4/35
377/376 [==============================] - 14s - loss: 0.0998    
Epoch 5/35
377/376 [==============================] - 14s - loss: 0.0985    
Epoch 6/35
377/376 [==============================] - 14s - loss: 0.0972    
Epoch 7/35
377/376 [==============================] - 14s - loss: 0.0960    
Epoch 8/35
377/376 [==============================] - 14s - loss: 0.0945    
Epoch 9/35
377/376 [==============================] - 14s - loss: 0.0934    
Epoch 10/35
377/376 [==============================] - 14s - loss: 0.0920

189/188 [==============================] - 4s - loss: 0.0714     
Epoch 28/35
189/188 [==============================] - 4s - loss: 0.0716     
Epoch 29/35
189/188 [==============================] - 4s - loss: 0.0711     
Epoch 30/35
189/188 [==============================] - 4s - loss: 0.0719     
Epoch 31/35
189/188 [==============================] - 4s - loss: 0.0717     
Epoch 32/35
189/188 [==============================] - 4s - loss: 0.0716     
Epoch 33/35
189/188 [==============================] - 4s - loss: 0.0711     
Epoch 34/35
189/188 [==============================] - 4s - loss: 0.0715     
Epoch 35/35
189/188 [==============================] - 4s - loss: 0.0717     


In [2]:
from keras import backend as K
import tensorflow as tf
K.clear_session()
sess = tf.Session()
K.set_session(sess)

## Without pretrained weights

In [3]:
datagen=ImageDataGenerator(samplewise_center=True,
    samplewise_std_normalization=True)

train_generator = datagen.flow_from_directory(
        TrainImagesPath,
        target_size=(128, 128),
        batch_size=batch_size,
        class_mode='categorical', seed=777)
train_count = train_generator.n
test_generator = datagen.flow_from_directory(
        TestImagesPath,
        target_size=(128, 128),
        batch_size=batch_size,
        class_mode='categorical',shuffle=False)
test_count = test_generator.n
#%%
model = Sequential()
model.add(Flatten(input_shape=(128,128,3),name='flatten'))
model.add(Dense(units=300, activation='sigmoid', name='dens_sigmoid_1'))
model.add(Dense(units=101, activation='softmax'))
#model.load_weights('DenseAutoEncoderNET1_weights', by_name=True)
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])
#%%
early_stopping=EarlyStopping(monitor='acc', patience=3, verbose=0, mode='auto')
t0=time.time()
model.fit_generator(train_generator,
        steps_per_epoch=train_count/batch_size,
        epochs=epochs,
        callbacks=[early_stopping])
t1=time.time()
loss_and_metrics = model.evaluate_generator(test_generator, steps=test_count/batch_size)
print('Accuracy =',loss_and_metrics[1])
print('Time =',(t1-t0))
#%%

Found 6026 images belonging to 101 classes.
Found 2651 images belonging to 101 classes.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Epoch 1/35
189/188 [==============================] - 12s - loss: 3.8608 - acc: 0.2099    
Epoch 2/35
189/188 [==============================] - 12s - loss: 3.3700 - acc: 0.2828    
Epoch 3/35
189/188 [==============================] - 12s - loss: 3.1446 - acc: 0.3136    
Epoch 4/35
189/188 [==============================] - 12s - loss: 2.9785 - acc: 0.3388    
Epoch 5/35
189/188 [==============================] - 12s - loss: 2.8342 - acc: 0.3723    
Epoch 6/35
189/188 [==============================] - 12s - loss: 2.7122 - acc: 0.4003    
Epoch 7/35
189/188 [==============================] - 12s - loss: 2.5922 - acc: 0.4356    
Epoch 8/35
189/188 [==============================] - 12s - loss: 2.4885 - acc: 0.4622    
Epoch 9/35
189/188 [==============================] - 12s - loss: 2.3873 - acc: 0.4927    
Epoch 10/35
189/188 

In [4]:
from keras import backend as K
import tensorflow as tf
K.clear_session()
sess = tf.Session()
K.set_session(sess)

In [6]:
pretrain_generator

In [7]:
model_1 = Sequential()
model_1.add(Flatten(input_shape=(128,128,3),name='flatten'))
model_1.add(Dense(units=300, activation='sigmoid', name='dens_sigmoid_1'))
model_1.add(Dense(units=101, activation='softmax'))
model_1.load_weights('DenseAutoEncoderNET1_weights_1', by_name=True)
model_1.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

## With pretrained weights

In [8]:
model_1 = Sequential()
model_1.add(Flatten(input_shape=(128,128,3),name='flatten'))
model_1.add(Dense(units=300, activation='sigmoid', name='dens_sigmoid_1'))
model_1.add(Dense(units=101, activation='softmax'))
model_1.load_weights('DenseAutoEncoderNET1_weights_1', by_name=True)
model_1.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])
#%%
early_stopping=EarlyStopping(monitor='acc', patience=3, verbose=0, mode='auto')
t0=time.time()
model_1.fit_generator(train_generator,
        steps_per_epoch=train_count/batch_size,
        epochs=epochs,
        callbacks=[early_stopping])
t1=time.time()
loss_and_metrics = model_1.evaluate_generator(test_generator, steps=test_count/batch_size)
print('Accuracy =',loss_and_metrics[1])
print('Time =',(t1-t0))
#%%

model_2 = Sequential()
model_2.add(Flatten(input_shape=(128,128,3),name='flatten'))
model_2.add(Dense(units=300, activation='sigmoid', name='dens_sigmoid_1'))
model_2.add(Dense(units=101, activation='softmax'))
model_2.load_weights('DenseAutoEncoderNET1_weights_2', by_name=True)
model_2.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])
#%%
early_stopping=EarlyStopping(monitor='acc', patience=3, verbose=0, mode='auto')
t0=time.time()
model_2.fit_generator(train_generator,
        steps_per_epoch=train_count/batch_size,
        epochs=epochs,
        callbacks=[early_stopping])
t1=time.time()
loss_and_metrics = model_2.evaluate_generator(test_generator, steps=test_count/batch_size)
print('Accuracy =',loss_and_metrics[1])
print('Time =',(t1-t0))
#%%

model_3 = Sequential()
model_3.add(Flatten(input_shape=(128,128,3),name='flatten'))
model_3.add(Dense(units=300, activation='sigmoid', name='dens_sigmoid_1'))
model_3.add(Dense(units=101, activation='softmax'))
model_3.load_weights('DenseAutoEncoderNET1_weights_3', by_name=True)
model_3.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])
#%%
early_stopping=EarlyStopping(monitor='acc', patience=3, verbose=0, mode='auto')
t0=time.time()
model_3.fit_generator(train_generator,
        steps_per_epoch=train_count/batch_size,
        epochs=epochs,
        callbacks=[early_stopping])
t1=time.time()
loss_and_metrics = model_3.evaluate_generator(test_generator, steps=test_count/batch_size)
print('Accuracy =',loss_and_metrics[1])
print('Time =',(t1-t0))
#%%

model_4 = Sequential()
model_4.add(Flatten(input_shape=(128,128,3),name='flatten'))
model_4.add(Dense(units=300, activation='sigmoid', name='dens_sigmoid_1'))
model_4.add(Dense(units=101, activation='softmax'))
model_4.load_weights('DenseAutoEncoderNET1_weights_4', by_name=True)
model_4.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])
#%%
early_stopping=EarlyStopping(monitor='acc', patience=3, verbose=0, mode='auto')
t0=time.time()
model_4.fit_generator(train_generator,
        steps_per_epoch=train_count/batch_size,
        epochs=epochs,
        callbacks=[early_stopping])
t1=time.time()
loss_and_metrics = model_4.evaluate_generator(test_generator, steps=test_count/batch_size)
print('Accuracy =',loss_and_metrics[1])
print('Time =',(t1-t0))
#%%

model_5 = Sequential()
model_5.add(Flatten(input_shape=(128,128,3),name='flatten'))
model_5.add(Dense(units=300, activation='sigmoid', name='dens_sigmoid_1'))
model_5.add(Dense(units=101, activation='softmax'))
model_5.load_weights('DenseAutoEncoderNET1_weights_5', by_name=True)
model_5.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])
#%%
early_stopping=EarlyStopping(monitor='acc', patience=3, verbose=0, mode='auto')
t0=time.time()
model_5.fit_generator(train_generator,
        steps_per_epoch=train_count/batch_size,
        epochs=epochs,
        callbacks=[early_stopping])
t1=time.time()
loss_and_metrics = model_5.evaluate_generator(test_generator, steps=test_count/batch_size)
print('Accuracy =',loss_and_metrics[1])
print('Time =',(t1-t0))

#%%
model_6 = Sequential()
model_6.add(Flatten(input_shape=(128,128,3),name='flatten'))
model_6.add(Dense(units=300, activation='sigmoid', name='dens_sigmoid_1'))
model_6.add(Dense(units=101, activation='softmax'))
model_6.load_weights('DenseAutoEncoderNET1_weights_6', by_name=True)
model_6.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])
#%%
early_stopping=EarlyStopping(monitor='acc', patience=3, verbose=0, mode='auto')
t0=time.time()
model_6.fit_generator(train_generator,
        steps_per_epoch=train_count/batch_size,
        epochs=epochs,
        callbacks=[early_stopping])
t1=time.time()
loss_and_metrics = model_6.evaluate_generator(test_generator, steps=test_count/batch_size)
print('Accuracy =',loss_and_metrics[1])
print('Time =',(t1-t0))

Epoch 1/35
189/188 [==============================] - 13s - loss: 4.1694 - acc: 0.1627    
Epoch 2/35
189/188 [==============================] - 12s - loss: 3.7617 - acc: 0.2263    
Epoch 3/35
189/188 [==============================] - 12s - loss: 3.5658 - acc: 0.2582    
Epoch 4/35
189/188 [==============================] - 12s - loss: 3.4252 - acc: 0.2780    
Epoch 5/35
189/188 [==============================] - 12s - loss: 3.3063 - acc: 0.2973    - ETA: 0s - loss: 3.3150
Epoch 6/35
189/188 [==============================] - 12s - loss: 3.2015 - acc: 0.3112    
Epoch 7/35
189/188 [==============================] - 12s - loss: 3.1069 - acc: 0.3237    
Epoch 8/35
189/188 [==============================] - 12s - loss: 3.0205 - acc: 0.3394    
Epoch 9/35
189/188 [==============================] - 12s - loss: 2.9399 - acc: 0.3542    
Epoch 10/35
189/188 [==============================] - 12s - loss: 2.8654 - acc: 0.3721    
Epoch 11/35
189/188 [==============================] - 12s - loss

Epoch 1/35
189/188 [==============================] - 12s - loss: 4.2809 - acc: 0.1293    
Epoch 2/35
189/188 [==============================] - 12s - loss: 3.9301 - acc: 0.2032    
Epoch 3/35
189/188 [==============================] - 12s - loss: 3.7658 - acc: 0.2261    
Epoch 4/35
189/188 [==============================] - 12s - loss: 3.6244 - acc: 0.2473    
Epoch 5/35
189/188 [==============================] - 12s - loss: 3.5043 - acc: 0.2647    
Epoch 6/35
189/188 [==============================] - 12s - loss: 3.4073 - acc: 0.2810    
Epoch 7/35
189/188 [==============================] - 12s - loss: 3.3060 - acc: 0.2936    
Epoch 8/35
189/188 [==============================] - 12s - loss: 3.2377 - acc: 0.3027    
Epoch 9/35
189/188 [==============================] - 12s - loss: 3.1512 - acc: 0.3212    
Epoch 10/35
189/188 [==============================] - 12s - loss: 3.0881 - acc: 0.3294    
Epoch 11/35
189/188 [==============================] - 12s - loss: 2.9948 - acc: 0.3493  

In [9]:
from keras import backend as K
import tensorflow as tf
K.clear_session()
sess = tf.Session()
K.set_session(sess)

# Dense NET2

## Autoencoder

In [10]:
# first layer's autoencoder
input_img = Input(shape=(img_width, img_height, 3))
x = Flatten(input_shape=(img_width, img_height, 3))(input_img)
encoded = (Dense(units=1000, activation='sigmoid', name='dens_sigmoid_1'))(x)
x = Dense(img_width*img_height*3, activation='sigmoid')(encoded)
decoded = Reshape((img_width, img_height, 3), input_shape=(img_width*img_height*3,))(x)

autoencoder1 = Model(input_img, decoded)

autoencoder1.compile(optimizer='adadelta', loss='mse')
print (autoencoder1.summary())
autoencoder1.fit_generator(
        tuple_generator(pretrain_generator),
        steps_per_epoch=train_samples/batch_size,
        epochs=epochs
        )
plot_model(autoencoder1, to_file='DenseAutoEncoder2_l1.png', show_shapes=True, show_layer_names=True, rankdir='LR')
autoencoder1.save('DenseAutoEncoderNET2_l1')
autoencoder1.save_weights('DenseAutoEncoderNET2_weights_l1')

encoder1 = Sequential()
encoder1.add(Flatten(input_shape=(img_width, img_height, 3)))
encoder1.add(Dense(units=1000, activation='sigmoid', name='dens_sigmoid_1'))
encoder1.load_weights('DenseAutoEncoderNET2_weights_l1', by_name=True)
encoder1.compile(optimizer='adadelta', loss='mse')
encoder1_out = (encoder1.predict_generator(tuple_generator(pretrain_generator),steps=train_samples/batch_size))
print (encoder1_out.shape)

# second layer's autoencoder
x = Input(shape=(1000,))
encoded = (Dense(units=500, activation='tanh', name='dens_tanh_1'))(x)
decoded = Dense(1000, activation='tanh')(encoded)

autoencoder2 = Model(x, decoded)
autoencoder2.compile(optimizer='adadelta', loss='mse')
print (autoencoder2.summary())
autoencoder2.fit(
        encoder1_out, encoder1_out,
        batch_size=batch_size,
        epochs=epochs
        )
plot_model(autoencoder2, to_file='DenseAutoEncoder2_l2.png', show_shapes=True, show_layer_names=True, rankdir='LR')
autoencoder2.save('DenseAutoEncoderNET2_l2')
autoencoder2.save_weights('DenseAutoEncoderNET2_weights_l2')

encoder2 = Sequential()
encoder2.add(Dense(units=500, activation='tanh', input_shape=(1000,), name='dens_tanh_1'))
encoder2.load_weights('DenseAutoEncoderNET2_weights_l2', by_name=True)
encoder2.compile(optimizer='adadelta', loss='mse')
encoder2_out = encoder2.predict(encoder1_out)

# third layer's autoencoder
x = Input(shape=(500,))
encoded = (Dense(units=300, activation='relu', name='dens_relu_1'))(x)
decoded = Dense(500, activation='relu')(encoded)

autoencoder3 = Model(x, decoded)
autoencoder3.compile(optimizer='adadelta', loss='mse')
print (autoencoder3.summary())
autoencoder3.fit(
        encoder2_out, encoder2_out,
        batch_size=batch_size,
        epochs=epochs
        )
plot_model(autoencoder3, to_file='DenseAutoEncoder2_l3png', show_shapes=True, show_layer_names=True, rankdir='LR')
autoencoder3.save('DenseAutoEncoderNET2_l3')
autoencoder3.save_weights('DenseAutoEncoderNET2_weights_l3')

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 128, 128, 3)       0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 49152)             0         
_________________________________________________________________
dens_sigmoid_1 (Dense)       (None, 1000)              49153000  
_________________________________________________________________
dense_1 (Dense)              (None, 49152)             49201152  
_________________________________________________________________
reshape_1 (Reshape)          (None, 128, 128, 3)       0         
Total params: 98,354,152
Trainable params: 98,354,152
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/35
189/188 [==============================] - 19s - loss: 0.1021    
Epoch 2/35
189/188 [============================

In [11]:
from keras import backend as K
import tensorflow as tf
K.clear_session()
sess = tf.Session()
K.set_session(sess)

## Without pretrained weights

In [12]:
model = Sequential()
model.add(Flatten(input_shape=(128,128,3)))
model.add(Dense(units=1000, activation='sigmoid', name='dens_sigmoid_1'))
model.add(Dense(units=500, activation='tanh', name='dens_tanh_1'))
model.add(Dense(units=300, activation='relu', name='dens_relu_1'))
model.add(Dense(units=101, activation='softmax'))
#model.load_weights('DenseAutoEncoderNET2_weights_l1', by_name=True)
#model.load_weights('DenseAutoEncoderNET2_weights_l2', by_name=True)
#model.load_weights('DenseAutoEncoderNET2_weights_l3', by_name=True)
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])
#%%
from keras.callbacks import EarlyStopping
early_stopping=EarlyStopping(monitor='acc', patience=3, verbose=0, mode='auto')
import time
t0=time.time()
model.fit_generator(train_generator,
        steps_per_epoch=train_count/batch_size,
        epochs=epochs,
        callbacks=[early_stopping])
t1=time.time()
loss_and_metrics = model.evaluate_generator(test_generator, steps=test_count/batch_size)
print('Accuracy =',loss_and_metrics[1])
print('Time =',(t1-t0))
#%%

Epoch 1/35
189/188 [==============================] - 13s - loss: 3.8080 - acc: 0.2344    
Epoch 2/35
189/188 [==============================] - 12s - loss: 3.3514 - acc: 0.2878    
Epoch 3/35
189/188 [==============================] - 12s - loss: 3.0944 - acc: 0.3272    
Epoch 4/35
189/188 [==============================] - 12s - loss: 2.8729 - acc: 0.3690    
Epoch 5/35
189/188 [==============================] - 12s - loss: 2.6861 - acc: 0.4101    
Epoch 6/35
189/188 [==============================] - 12s - loss: 2.5309 - acc: 0.4459    
Epoch 7/35
189/188 [==============================] - 12s - loss: 2.3497 - acc: 0.4869    
Epoch 8/35
189/188 [==============================] - 12s - loss: 2.2022 - acc: 0.5329    
Epoch 9/35
189/188 [==============================] - 12s - loss: 2.0476 - acc: 0.5736    
Epoch 10/35
189/188 [==============================] - 12s - loss: 1.9202 - acc: 0.6076    
Epoch 11/35
189/188 [==============================] - 12s - loss: 1.7917 - acc: 0.6482  

In [13]:
from keras import backend as K
import tensorflow as tf
K.clear_session()
sess = tf.Session()
K.set_session(sess)

## With pretrained weights

In [22]:
model = Sequential()
model.add(Flatten(input_shape=(128,128,3)))
model.add(Dense(units=1000, activation='sigmoid', name='dens_sigmoid_1'))
model.add(Dense(units=500, activation='tanh', name='dens_tanh_1'))
model.add(Dense(units=300, activation='relu', name='dens_relu_1'))
model.add(Dense(units=101, activation='softmax'))
model.load_weights('DenseAutoEncoderNET2_weights_l1', by_name=True)
model.load_weights('DenseAutoEncoderNET2_weights_l2', by_name=True)
model.load_weights('DenseAutoEncoderNET2_weights_l3', by_name=True)
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])
#%%
from keras.callbacks import EarlyStopping
early_stopping=EarlyStopping(monitor='acc', patience=3, verbose=0, mode='auto')
import time
t0=time.time()
model.fit_generator(train_generator,
        steps_per_epoch=train_count/batch_size,
        epochs=epochs,
        callbacks=[early_stopping])
t1=time.time()
loss_and_metrics = model.evaluate_generator(test_generator, steps=test_count/batch_size)
print('Accuracy =',loss_and_metrics[1])
print('Time =',(t1-t0))
#%%

Epoch 1/35
189/188 [==============================] - 13s - loss: 4.0606 - acc: 0.1783    
Epoch 2/35
189/188 [==============================] - 12s - loss: 3.6509 - acc: 0.2518    
Epoch 3/35
189/188 [==============================] - 12s - loss: 3.4014 - acc: 0.2857    
Epoch 4/35
189/188 [==============================] - 12s - loss: 3.2195 - acc: 0.3087    
Epoch 5/35
189/188 [==============================] - 12s - loss: 3.0472 - acc: 0.3385    
Epoch 6/35
189/188 [==============================] - 12s - loss: 2.9006 - acc: 0.3693    
Epoch 7/35
189/188 [==============================] - 12s - loss: 2.7526 - acc: 0.4034    
Epoch 8/35
189/188 [==============================] - 12s - loss: 2.6218 - acc: 0.4307    
Epoch 9/35
189/188 [==============================] - 12s - loss: 2.4786 - acc: 0.4597    
Epoch 10/35
189/188 [==============================] - 12s - loss: 2.3560 - acc: 0.4911    
Epoch 11/35
189/188 [==============================] - 12s - loss: 2.2476 - acc: 0.5209  

In [ ]:
from keras import backend as K
import tensorflow as tf
K.clear_session()
sess = tf.Session()
K.set_session(sess)

In [1]:
from keras.preprocessing.image import ImageDataGenerator
from keras.layers import Input, Dense, Flatten, Reshape, Dropout, Conv2D, MaxPooling2D, UpSampling2D
from keras.models import Model, Sequential
from keras.utils import plot_model
from keras.callbacks import EarlyStopping
from keras.optimizers import SGD
import time
import numpy as np
import matplotlib.pyplot as plt
import sys

def tuple_generator(generator):
    for batch in generator:
        yield (batch, batch)

np.random.seed(777)
#if (len(sys.argv)<3):
#    print("Input arguments:")
#    print("1. Train images path")
#    print("2. Test images path")
#    exit()
PreTrainImagesPath="D:/SomeData/Caltech101/TrainImages"
PreTestImagesPath="D:/SomeData/Caltech101/TestImages"
TrainImagesPath="D:/SomeData/Caltech101/TrainImages"
TestImagesPath="D:/SomeData/Caltech101/TestImages"
img_width, img_height = 128, 128
epochs = 35
batch_size_1 = 16
batch_size = 32
batch_size_3 = 64
dropout_rate = 0.3
latent_dim = 101

datagen=ImageDataGenerator(rescale=1./255)
pretrain_generator = datagen.flow_from_directory(
        PreTrainImagesPath,
        target_size=(img_width, img_height),
        batch_size=batch_size,
        class_mode=None)
train_samples = pretrain_generator.n

validation_generator = datagen.flow_from_directory(
        PreTestImagesPath,
        target_size=(img_width, img_height),
        batch_size=batch_size,
        class_mode=None)
nb_validation_samples = validation_generator.n

sgd_4 = SGD(lr=0.1, decay=1e-6, momentum=0.9, nesterov=True)
sgd_5 = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
sgd_6 = SGD(lr=0.001, decay=1e-6, momentum=0.9, nesterov=True)

Using TensorFlow backend.


Found 6026 images belonging to 101 classes.
Found 2651 images belonging to 101 classes.


In [2]:
epochs = 10

# Conv NET1

## Autoencoder

In [ ]:
# first layer's autoencoder
input_img = Input(shape=(img_width, img_height, 3))
x = Conv2D(32, (3, 3), activation='tanh', padding='same', input_shape=(img_width,img_height,3), name='conv_tanh_1')(input_img)
x = Conv2D(32, (3, 3), activation='tanh', padding='same', name='conv_tanh_2')(x)
x = MaxPooling2D((2, 2), padding='same', name='maxpool_1')(x)
encoded = Dropout((0.25), name='dropout_1')(x)
x = UpSampling2D((2, 2))(encoded)
x = Conv2D(32, (3, 3), activation='tanh', padding='same')(x)
decoded = Conv2D(3, (3, 3), activation='tanh', padding='same')(x)

autoencoder1 = Model(input_img, decoded)

autoencoder1.compile(optimizer='adadelta', loss='mse')
print (autoencoder1.summary())
autoencoder1.fit_generator(
        tuple_generator(pretrain_generator),
        steps_per_epoch=train_samples/batch_size,
        epochs=epochs
        )
plot_model(autoencoder1, to_file='ConvAutoEncoder2_l1.png', show_shapes=True, show_layer_names=True, rankdir='LR')
autoencoder1.save('ConvAutoEncoderNET1_l1')
autoencoder1.save_weights('ConvAutoEncoderNET1_weights_l1')

Instructions for updating:
keep_dims is deprecated, use keepdims instead
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 128, 128, 3)       0         
_________________________________________________________________
conv_tanh_1 (Conv2D)         (None, 128, 128, 32)      896       
_________________________________________________________________
conv_tanh_2 (Conv2D)         (None, 128, 128, 32)      9248      
_________________________________________________________________
maxpool_1 (MaxPooling2D)     (None, 64, 64, 32)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 64, 64, 32)        0         
_________________________________________________________________
up_sampling2d_1 (UpSampling2 (None, 128, 128, 32)      0         
_________________________________________________________________
con

In [4]:
encoder1 = Sequential()
encoder1.add(Conv2D(32, (3, 3), activation='tanh', padding='same', input_shape=(img_width,img_height,3), name='conv_tanh_1'))
encoder1.add(Conv2D(32, (3, 3), activation='tanh', padding='same', name='conv_tanh_2'))
encoder1.add(MaxPooling2D((2, 2), padding='same', name='maxpool_1'))
encoder1.add(Dropout((0.25), name='dropout_1'))
encoder1.add(Flatten(input_shape=(64, 64, 32)))
encoder1.load_weights('ConvAutoEncoderNET1_weights_l1', by_name=True)
encoder1.compile(optimizer='adadelta', loss='mse')
encoder1_out = (encoder1.predict_generator(tuple_generator(pretrain_generator),steps=train_samples/(batch_size*10)))
print (encoder1_out.shape)

Instructions for updating:
keep_dims is deprecated, use keepdims instead
Instructions for updating:
keep_dims is deprecated, use keepdims instead
(608, 131072)


In [5]:
# second layer's autoencoder
input_ = Input(shape=(131072,))
x = Dense(units=512, activation='tanh', name='dense_tanh_1')(input_)
encoded = Dropout((0.5), name='dropout_2')(x)
x = Dense(units=512, activation='tanh')(encoded)
decoded = Dense(units=131072)(x)

autoencoder2 = Model(input_, decoded)
autoencoder2.compile(optimizer='adadelta', loss='mse')
print (autoencoder2.summary())
autoencoder2.fit(
        encoder1_out, encoder1_out,
        batch_size=batch_size,
        epochs=epochs
        )
plot_model(autoencoder2, to_file='ConvAutoEncoder2_l2.png', show_shapes=True, show_layer_names=True, rankdir='LR')
autoencoder2.save('ConvAutoEncoderNET1_l2')
autoencoder2.save_weights('ConvAutoEncoderNET1_weights_l2')

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 131072)            0         
_________________________________________________________________
dense_tanh_1 (Dense)         (None, 512)               67109376  
_________________________________________________________________
dropout_2 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 512)               262656    
_________________________________________________________________
dense_2 (Dense)              (None, 131072)            67239936  
Total params: 134,611,968
Trainable params: 134,611,968
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/10
608/608 [==============================] - 7s - loss: 0.0106     
Epoch 2/10
608/608 [==========================

In [5]:
from keras import backend as K
import tensorflow as tf
K.clear_session()
sess = tf.Session()
K.set_session(sess)

In [1]:
from keras.preprocessing.image import ImageDataGenerator
from keras.layers import Input, Dense, Flatten, Reshape, Dropout, Conv2D, MaxPooling2D, UpSampling2D
from keras.models import Model, Sequential
from keras.utils import plot_model
from keras.callbacks import EarlyStopping
from keras.optimizers import SGD
import time
import numpy as np
import matplotlib.pyplot as plt
import sys

def tuple_generator(generator):
    for batch in generator:
        yield (batch, batch)

np.random.seed(777)
#if (len(sys.argv)<3):
#    print("Input arguments:")
#    print("1. Train images path")
#    print("2. Test images path")
#    exit()
PreTrainImagesPath="D:/SomeData/Caltech101/TrainImages"
PreTestImagesPath="D:/SomeData/Caltech101/TestImages"
TrainImagesPath="D:/SomeData/Caltech101/TrainImages"
TestImagesPath="D:/SomeData/Caltech101/TestImages"
img_width, img_height = 128, 128
epochs = 35
batch_size_1 = 16
batch_size = 32
batch_size_3 = 64
dropout_rate = 0.3
latent_dim = 101

datagen=ImageDataGenerator(rescale=1./255)
train_generator = datagen.flow_from_directory(
        PreTrainImagesPath,
        target_size=(img_width, img_height),
        batch_size=batch_size,
        class_mode=None)
train_samples = train_generator.n

test_generator = datagen.flow_from_directory(
        PreTestImagesPath,
        target_size=(img_width, img_height),
        batch_size=batch_size,
        class_mode=None)
nb_validation_samples = test_generator.n

sgd_4 = SGD(lr=0.1, decay=1e-6, momentum=0.9, nesterov=True)
sgd_5 = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
sgd_6 = SGD(lr=0.001, decay=1e-6, momentum=0.9, nesterov=True)

Using TensorFlow backend.


Found 6026 images belonging to 101 classes.
Found 2651 images belonging to 101 classes.


## Without pretrained weights

In [2]:
epochs = 35
batch = 32
dropout_rate = 0.3
latent_dim = 101
train_count=6026
test_count=2651

In [3]:
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='tanh', padding='same', input_shape=(128,128,3), name='conv_tanh_1'))
model.add(Conv2D(32, (3, 3), activation='tanh', padding='same', name='conv_tanh_2'))
model.add(MaxPooling2D(pool_size=(2, 2), padding='same', name='maxpool_1'))
model.add(Dropout(0.25, name='dropout_1'))
model.add(Flatten(name='flat_1'))
model.add(Dense(512, activation='tanh', name='dense_tanh_1'))
model.add(Dropout(0.5, name='dropout_2'))
model.add(Dense(101, activation='softmax', name='dense_softmax_1'))
#model.load_weights('ConvAutoEncoderNET1_weights_l1', by_name=True)
#model.load_weights('ConvAutoEncoderNET1_weights_l2', by_name=True)
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

Instructions for updating:
keep_dims is deprecated, use keepdims instead
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Instructions for updating:
keep_dims is deprecated, use keepdims instead


In [4]:
early_stopping=EarlyStopping(monitor='acc', patience=3, verbose=0, mode='auto')
t0=time.time()
model.fit_generator(train_generator,
        steps_per_epoch=train_count//batch,
        epochs=epochs,
        callbacks=[early_stopping])
t1=time.time()
loss_and_metrics = model.evaluate_generator(test_generator, steps=test_count/batch)
print('Accuracy =',loss_and_metrics[1])
print('Time =',(t1-t0))
#%%

Epoch 1/35


ValueError: Output of generator should be a tuple `(x, y, sample_weight)` or `(x, y)`. Found: [[[[ 0.47058827  0.63529414  0.7843138 ]
   [ 0.45882356  0.62352943  0.77254909]
   [ 0.46274513  0.627451    0.77647066]
   ..., 
   [ 0.83529419  0.86666673  0.94117653]
   [ 0.86666673  0.89411771  0.96470594]
   [ 0.87843144  0.89803928  0.97254908]]

  [[ 0.45490199  0.61960787  0.76862752]
   [ 0.44313729  0.60784316  0.75686282]
   [ 0.44705886  0.61176473  0.76078439]
   ..., 
   [ 0.82352948  0.85490203  0.92941183]
   [ 0.85098046  0.87843144  0.95294124]
   [ 0.86274517  0.88235301  0.95686281]]

  [[ 0.45490199  0.61960787  0.76862752]
   [ 0.43921572  0.60392159  0.75294125]
   [ 0.43921572  0.60392159  0.75294125]
   ..., 
   [ 0.80392164  0.83137262  0.90588242]
   [ 0.82745105  0.85490203  0.92941183]
   [ 0.83921576  0.8588236   0.9333334 ]]

  ..., 
  [[ 0.36078432  0.33333334  0.36470589]
   [ 0.32549021  0.29803923  0.32941177]
   [ 0.32156864  0.3019608   0.32941177]
   ..., 
   [ 0.27843139  0.27450982  0.30588236]
   [ 0.28627452  0.28627452  0.31764707]
   [ 0.28235295  0.28235295  0.3137255 ]]

  [[ 0.2392157   0.21568629  0.25490198]
   [ 0.21568629  0.19215688  0.23137257]
   [ 0.2392157   0.21568629  0.25490198]
   ..., 
   [ 0.25490198  0.25098041  0.28235295]
   [ 0.25882354  0.25882354  0.29019609]
   [ 0.25490198  0.25490198  0.28627452]]

  [[ 0.38431376  0.36078432  0.40000004]
   [ 0.34117648  0.31764707  0.35686275]
   [ 0.32156864  0.30980393  0.35294119]
   ..., 
   [ 0.26666668  0.26274511  0.29411766]
   [ 0.26666668  0.26666668  0.29803923]
   [ 0.25882354  0.25882354  0.29019609]]]


 [[[ 1.          0.98039222  1.        ]
   [ 1.          0.98431379  1.        ]
   [ 0.99215692  0.99215692  0.99215692]
   ..., 
   [ 0.98823535  0.99607849  0.99215692]
   [ 0.98823535  0.99607849  0.99215692]
   [ 0.98823535  0.99607849  0.99215692]]

  [[ 1.          0.98039222  1.        ]
   [ 1.          0.98431379  1.        ]
   [ 0.99215692  0.99215692  0.99215692]
   ..., 
   [ 0.98823535  0.99607849  0.99215692]
   [ 0.98823535  0.99607849  0.99215692]
   [ 0.98823535  0.99607849  0.99215692]]

  [[ 1.          0.98039222  1.        ]
   [ 1.          0.98431379  1.        ]
   [ 0.99215692  0.99215692  0.99215692]
   ..., 
   [ 0.98823535  0.99607849  0.99215692]
   [ 0.98823535  0.99607849  0.99215692]
   [ 0.98823535  0.99607849  0.99215692]]

  ..., 
  [[ 0.98823535  0.99607849  0.99215692]
   [ 0.98823535  0.99607849  0.99215692]
   [ 0.98823535  0.99607849  0.99215692]
   ..., 
   [ 0.97647065  1.          0.99215692]
   [ 0.96862751  1.          0.99215692]
   [ 0.96862751  1.          0.99215692]]

  [[ 0.98823535  0.99607849  0.99215692]
   [ 0.98823535  0.99607849  0.99215692]
   [ 0.98823535  0.99607849  0.99215692]
   ..., 
   [ 0.97647065  1.          0.99215692]
   [ 0.96862751  1.          0.99215692]
   [ 0.96862751  1.          0.99215692]]

  [[ 0.98823535  0.99607849  0.99215692]
   [ 0.98823535  0.99607849  0.99215692]
   [ 0.98823535  0.99607849  0.99215692]
   ..., 
   [ 0.97647065  1.          0.99215692]
   [ 0.96862751  1.          0.99215692]
   [ 0.96470594  1.          0.99215692]]]


 [[[ 0.65490198  0.30980393  0.01960784]
   [ 0.63921571  0.29411766  0.00392157]
   [ 0.63921571  0.28235295  0.00784314]
   ..., 
   [ 0.59607846  0.24705884  0.01176471]
   [ 0.58039218  0.24705884  0.        ]
   [ 0.56862748  0.24313727  0.        ]]

  [[ 0.63921571  0.29411766  0.01176471]
   [ 0.63137257  0.28627452  0.00392157]
   [ 0.627451    0.26666668  0.00392157]
   ..., 
   [ 0.59607846  0.24705884  0.01176471]
   [ 0.59215689  0.25882354  0.00784314]
   [ 0.59607846  0.27058825  0.01176471]]

  [[ 0.627451    0.27843139  0.01176471]
   [ 0.62352943  0.27450982  0.00784314]
   [ 0.61960787  0.27058825  0.01176471]
   ..., 
   [ 0.57254905  0.22352943  0.        ]
   [ 0.57647061  0.2392157   0.        ]
   [ 0.59215689  0.26274511  0.01176471]]

  ..., 
  [[ 0.05490196  0.05490196  0.05490196]
   [ 0.05490196  0.05490196  0.05490196]
   [ 0.05490196  0.05490196  0.05490196]
   ..., 
   [ 0.18823531  0.10980393  0.11764707]
   [ 0.18823531  0.10980393  0.11764707]
   [ 0.18823531  0.10196079  0.1137255 ]]

  [[ 0.01176471  0.01176471  0.01176471]
   [ 0.01176471  0.01176471  0.01176471]
   [ 0.01176471  0.01176471  0.01176471]
   ..., 
   [ 0.10588236  0.02745098  0.03529412]
   [ 0.10588236  0.02745098  0.03529412]
   [ 0.10980393  0.02352941  0.03529412]]

  [[ 0.00392157  0.00392157  0.00392157]
   [ 0.00392157  0.00392157  0.00392157]
   [ 0.00392157  0.00392157  0.00392157]
   ..., 
   [ 0.07843138  0.          0.00784314]
   [ 0.08235294  0.          0.00784314]
   [ 0.08235294  0.          0.00784314]]]


 ..., 
 [[[ 1.          0.99215692  0.96862751]
   [ 1.          0.99215692  0.97647065]
   [ 1.          0.99215692  0.98039222]
   ..., 
   [ 0.41960788  0.3921569   0.36078432]
   [ 0.24705884  0.21960786  0.19607845]
   [ 0.13725491  0.11764707  0.09411766]]

  [[ 1.          0.99215692  0.97647065]
   [ 1.          0.99607849  0.97647065]
   [ 1.          0.99215692  0.98039222]
   ..., 
   [ 0.75686282  0.72941178  0.69803923]
   [ 0.79215693  0.76470596  0.74117649]
   [ 0.59607846  0.57647061  0.56078434]]

  [[ 1.          0.99215692  0.98039222]
   [ 1.          0.99215692  0.98039222]
   [ 1.          0.99607849  0.98039222]
   ..., 
   [ 0.56470591  0.53725493  0.51372552]
   [ 0.49019611  0.47058827  0.44705886]
   [ 0.34509805  0.32549021  0.30980393]]

  ..., 
  [[ 0.28627452  0.18431373  0.07843138]
   [ 0.27843139  0.17647059  0.07058824]
   [ 0.29411766  0.19215688  0.08627451]
   ..., 
   [ 0.43529415  0.40000004  0.27058825]
   [ 0.54901963  0.49803925  0.37254903]
   [ 0.48235297  0.43137258  0.30588236]]

  [[ 0.55686277  0.45098042  0.34509805]
   [ 0.52549022  0.41960788  0.3137255 ]
   [ 0.50980395  0.4039216   0.29803923]
   ..., 
   [ 0.90980399  0.88627458  0.75294125]
   [ 0.45098042  0.41568631  0.28627452]
   [ 0.49411768  0.45098042  0.32549021]]

  [[ 0.50588238  0.40000004  0.29411766]
   [ 0.47058827  0.36470589  0.25882354]
   [ 0.45882356  0.35294119  0.24705884]
   ..., 
   [ 0.60392159  0.58823532  0.45098042]
   [ 0.50980395  0.48627454  0.35294119]
   [ 0.74117649  0.70588237  0.57647061]]]


 [[[ 0.          0.01960784  0.        ]
   [ 0.03137255  0.05490196  0.00784314]
   [ 0.01568628  0.03921569  0.        ]
   ..., 
   [ 0.01960784  0.09019608  0.09019608]
   [ 0.02352941  0.09411766  0.09411766]
   [ 0.02745098  0.09803922  0.09803922]]

  [[ 0.          0.01176471  0.        ]
   [ 0.01960784  0.04313726  0.        ]
   [ 0.          0.01960784  0.        ]
   ..., 
   [ 0.01568628  0.07843138  0.07843138]
   [ 0.          0.0627451   0.0627451 ]
   [ 0.          0.0509804   0.0509804 ]]

  [[ 0.17647059  0.20000002  0.15294118]
   [ 0.12941177  0.15294118  0.10588236]
   [ 0.03921569  0.0627451   0.01568628]
   ..., 
   [ 0.02745098  0.09019608  0.09019608]
   [ 0.00784314  0.07058824  0.07058824]
   [ 0.          0.0627451   0.0627451 ]]

  ..., 
  [[ 0.0509804   0.0509804   0.0509804 ]
   [ 0.01568628  0.01568628  0.01568628]
   [ 0.03529412  0.03529412  0.03529412]
   ..., 
   [ 0.08627451  0.06666667  0.08235294]
   [ 0.05882353  0.03529412  0.0509804 ]
   [ 0.04313726  0.00784314  0.02745098]]

  [[ 0.02745098  0.02745098  0.02745098]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   ..., 
   [ 0.06666667  0.04705883  0.0627451 ]
   [ 0.04313726  0.00784314  0.02745098]
   [ 0.04705883  0.01176471  0.03137255]]

  [[ 0.00784314  0.00784314  0.00784314]
   [ 0.02352941  0.02352941  0.02352941]
   [ 0.00392157  0.00392157  0.00392157]
   ..., 
   [ 0.01176471  0.          0.00784314]
   [ 0.02352941  0.          0.00784314]
   [ 0.03921569  0.          0.01960784]]]


 [[[ 0.08235294  0.22352943  0.41960788]
   [ 0.09803922  0.2392157   0.43529415]
   [ 0.10980393  0.25098041  0.44705886]
   ..., 
   [ 0.08235294  0.20392159  0.38823533]
   [ 0.09019608  0.21176472  0.39607847]
   [ 0.09019608  0.21176472  0.39607847]]

  [[ 0.01568628  0.15686275  0.35294119]
   [ 0.02352941  0.16470589  0.36078432]
   [ 0.03529412  0.17647059  0.37254903]
   ..., 
   [ 0.0627451   0.18823531  0.37254903]
   [ 0.07450981  0.20000002  0.38431376]
   [ 0.09019608  0.21568629  0.40000004]]

  [[ 0.09019608  0.23137257  0.42745101]
   [ 0.08235294  0.22352943  0.41960788]
   [ 0.07843138  0.21960786  0.41568631]
   ..., 
   [ 0.05882353  0.18431373  0.36862746]
   [ 0.07843138  0.20392159  0.38823533]
   [ 0.09803922  0.22352943  0.40784317]]

  ..., 
  [[ 0.25490198  0.46274513  0.67450982]
   [ 0.25098041  0.45882356  0.67058825]
   [ 0.25098041  0.45882356  0.67058825]
   ..., 
   [ 0.22352943  0.42352945  0.60000002]
   [ 0.22352943  0.42352945  0.60000002]
   [ 0.227451    0.42745101  0.60392159]]

  [[ 0.25098041  0.45882356  0.67058825]
   [ 0.25098041  0.45882356  0.67058825]
   [ 0.25490198  0.46274513  0.67450982]
   ..., 
   [ 0.22352943  0.42352945  0.60000002]
   [ 0.22352943  0.42352945  0.60000002]
   [ 0.22352943  0.42352945  0.60000002]]

  [[ 0.24705884  0.45490199  0.66666669]
   [ 0.25098041  0.45882356  0.67058825]
   [ 0.25882354  0.4666667   0.67843139]
   ..., 
   [ 0.22352943  0.42352945  0.60000002]
   [ 0.22352943  0.42352945  0.60000002]
   [ 0.22352943  0.42352945  0.60000002]]]]

In [ ]:
from keras import backend as K
import tensorflow as tf
K.clear_session()
sess = tf.Session()
K.set_session(sess)

## With pretrained weights

In [6]:
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='tanh', padding='same', input_shape=(128,128,3), name='conv_tanh_1'))
model.add(Conv2D(32, (3, 3), activation='tanh', padding='same', name='conv_tanh_2'))
model.add(MaxPooling2D(pool_size=(2, 2), padding='same', name='maxpool_1'))
model.add(Dropout(0.25, name='dropout_1'))
model.add(Flatten(name='flat_1'))
model.add(Dense(512, activation='tanh', name='dense_tanh_1'))
model.add(Dropout(0.5, name='dropout_2'))
model.add(Dense(101, activation='softmax', name='dense_softmax_1'))
model.load_weights('ConvAutoEncoderNET1_weights_l1', by_name=True)
#model.load_weights('ConvAutoEncoderNET1_weights_l2', by_name=True)
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])
#%%
early_stopping=EarlyStopping(monitor='acc', patience=3, verbose=0, mode='auto')
t0=time.time()
model.fit_generator(train_generator,
        steps_per_epoch=train_count/batch,
        epochs=epochs,
        callbacks=[early_stopping])
t1=time.time()
loss_and_metrics = model.evaluate_generator(test_generator, steps=test_count/batch)
print('Accuracy =',loss_and_metrics[1])
print('Time =',(t1-t0))
#%%

Epoch 1/35


ValueError: Output of generator should be a tuple `(x, y, sample_weight)` or `(x, y)`. Found: [[[[ 0.00392157  0.          0.        ]
   [ 0.05490196  0.04705883  0.0509804 ]
   [ 0.05882353  0.0509804   0.05490196]
   ..., 
   [ 0.03921569  0.03137255  0.04313726]
   [ 0.04313726  0.03529412  0.05490196]
   [ 0.01568628  0.00784314  0.02745098]]

  [[ 0.07843138  0.07058824  0.07450981]
   [ 0.0509804   0.04313726  0.04705883]
   [ 0.00392157  0.          0.        ]
   ..., 
   [ 0.03137255  0.02352941  0.03529412]
   [ 0.04313726  0.03529412  0.04705883]
   [ 0.01568628  0.00784314  0.01960784]]

  [[ 0.03529412  0.02745098  0.03137255]
   [ 0.00392157  0.          0.        ]
   [ 0.06666667  0.05882353  0.0627451 ]
   ..., 
   [ 0.02745098  0.01960784  0.03137255]
   [ 0.04705883  0.02745098  0.04313726]
   [ 0.01960784  0.          0.01568628]]

  ..., 
  [[ 0.19215688  0.21176472  0.13333334]
   [ 0.17647059  0.19607845  0.11764707]
   [ 0.15294118  0.17254902  0.09411766]
   ..., 
   [ 0.13725491  0.14509805  0.09019608]
   [ 0.10980393  0.11764707  0.0627451 ]
   [ 0.02352941  0.03137255  0.        ]]

  [[ 0.19215688  0.21176472  0.1254902 ]
   [ 0.18039216  0.20000002  0.1137255 ]
   [ 0.16078432  0.18039216  0.09411766]
   ..., 
   [ 0.24705884  0.25882354  0.19215688]
   [ 0.18823531  0.19607845  0.14117648]
   [ 0.01960784  0.02745098  0.        ]]

  [[ 0.14117648  0.16078432  0.07450981]
   [ 0.15294118  0.17254902  0.08627451]
   [ 0.16470589  0.18431373  0.09803922]
   ..., 
   [ 0.32941177  0.34117648  0.26666668]
   [ 0.24313727  0.25490198  0.18823531]
   [ 0.          0.01176471  0.        ]]]


 [[[ 0.84705889  0.84705889  0.84705889]
   [ 0.95686281  0.95686281  0.95686281]
   [ 0.76862752  0.76862752  0.76862752]
   ..., 
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]]

  [[ 0.56078434  0.56078434  0.56078434]
   [ 0.82352948  0.82352948  0.82352948]
   [ 0.80000007  0.80000007  0.80000007]
   ..., 
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]]

  [[ 1.          1.          1.        ]
   [ 0.78039223  0.78039223  0.78039223]
   [ 0.78823537  0.78823537  0.78823537]
   ..., 
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]]

  ..., 
  [[ 0.6901961   0.6901961   0.6901961 ]
   [ 0.63137257  0.63137257  0.63137257]
   [ 0.66274512  0.66274512  0.66274512]
   ..., 
   [ 0.96078438  0.96078438  0.96078438]
   [ 0.97254908  0.97254908  0.97254908]
   [ 1.          1.          1.        ]]

  [[ 0.99215692  0.99215692  0.99215692]
   [ 0.91764712  0.91764712  0.91764712]
   [ 1.          1.          1.        ]
   ..., 
   [ 0.98823535  0.98823535  0.98823535]
   [ 0.98823535  0.98823535  0.98823535]
   [ 0.98823535  0.98823535  0.98823535]]

  [[ 0.76470596  0.76470596  0.76470596]
   [ 0.80784321  0.80784321  0.80784321]
   [ 0.78823537  0.78823537  0.78823537]
   ..., 
   [ 0.99607849  0.99607849  0.99607849]
   [ 1.          1.          1.        ]
   [ 0.99215692  0.99215692  0.99215692]]]


 [[[ 1.          1.          1.        ]
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]
   ..., 
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]]

  [[ 1.          1.          1.        ]
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]
   ..., 
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]]

  [[ 1.          1.          1.        ]
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]
   ..., 
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]]

  ..., 
  [[ 0.90980399  0.90980399  0.90980399]
   [ 0.96078438  0.96078438  0.96078438]
   [ 1.          1.          1.        ]
   ..., 
   [ 0.90588242  0.90588242  0.90588242]
   [ 0.93725497  0.93725497  0.93725497]
   [ 0.99607849  0.99607849  0.99607849]]

  [[ 1.          1.          1.        ]
   [ 0.98039222  0.98039222  0.98039222]
   [ 0.97647065  0.97647065  0.97647065]
   ..., 
   [ 1.          1.          1.        ]
   [ 0.97647065  0.97647065  0.97647065]
   [ 1.          1.          1.        ]]

  [[ 0.96078438  0.96078438  0.96078438]
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]
   ..., 
   [ 0.95294124  0.95294124  0.95294124]
   [ 1.          1.          1.        ]
   [ 0.98823535  0.98823535  0.98823535]]]


 ..., 
 [[[ 0.9333334   0.84313732  0.        ]
   [ 0.8705883   0.7960785   0.01960784]
   [ 0.96078438  0.91764712  0.25882354]
   ..., 
   [ 1.          0.96862751  0.54901963]
   [ 0.99215692  0.88235301  0.25098041]
   [ 1.          0.99215692  0.17647059]]

  [[ 0.88627458  0.7019608   0.        ]
   [ 0.76078439  0.59215689  0.        ]
   [ 0.93725497  0.80000007  0.23529413]
   ..., 
   [ 0.97647065  0.80000007  0.39607847]
   [ 0.96862751  0.81176478  0.19215688]
   [ 0.98039222  0.84313732  0.03529412]]

  [[ 0.9450981   0.67450982  0.03529412]
   [ 0.7960785   0.5411765   0.        ]
   [ 1.          0.83921576  0.4039216 ]
   ..., 
   [ 0.80784321  0.6156863   0.3137255 ]
   [ 1.          0.81568635  0.30588236]
   [ 0.93725497  0.77254909  0.06666667]]

  ..., 
  [[ 0.91372555  0.7019608   0.03529412]
   [ 0.76862752  0.56862748  0.        ]
   [ 0.72549021  0.5411765   0.        ]
   ..., 
   [ 0.74509805  0.57647061  0.        ]
   [ 0.76470596  0.58039218  0.        ]
   [ 0.81176478  0.62352943  0.        ]]

  [[ 1.          0.79215693  0.18823531]
   [ 0.91372555  0.69803923  0.09019608]
   [ 0.80000007  0.60000002  0.        ]
   ..., 
   [ 0.81568635  0.61176473  0.08235294]
   [ 0.7960785   0.58039218  0.01568628]
   [ 0.85490203  0.63137257  0.03529412]]

  [[ 0.95294124  0.71372551  0.15294118]
   [ 0.96078438  0.73333335  0.16862746]
   [ 0.91372555  0.7019608   0.12156864]
   ..., 
   [ 0.90980399  0.68235296  0.25098041]
   [ 0.86274517  0.62352943  0.16470589]
   [ 0.92156869  0.67058825  0.18431373]]]


 [[[ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   ..., 
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]]

  [[ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   ..., 
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]]

  [[ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   ..., 
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]]

  ..., 
  [[ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   ..., 
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]]

  [[ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   ..., 
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]]

  [[ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   ..., 
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]]]


 [[[ 1.          1.          1.        ]
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]
   ..., 
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]]

  [[ 1.          1.          1.        ]
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]
   ..., 
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]]

  [[ 1.          1.          1.        ]
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]
   ..., 
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]]

  ..., 
  [[ 1.          1.          1.        ]
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]
   ..., 
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]]

  [[ 1.          1.          1.        ]
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]
   ..., 
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]]

  [[ 1.          1.          1.        ]
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]
   ..., 
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]
   [ 1.          1.          1.        ]]]]